# Generated by Django 6.0.2 on 2026-05-07 00:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_cliente_documento'),
        ('estoque_rodas', '0005_roda_quantidade_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('orcamento', 'Orçamento'), ('reservada_nao_paga', 'Reservada - não paga'), ('reservada_paga', 'Reservada - paga'), ('aguardando_pagamento', 'Aguardando pagamento'), ('paga_aguardando_retirada', 'Paga - aguardando retirada'), ('paga_aguardando_entrega', 'Paga - aguardando entrega'), ('finalizada_retirada', 'Finalizada - retirada pelo cliente'), ('finalizada_entregue', 'Finalizada - entregue'), ('cancelada', 'Cancelada')], default='orcamento', max_length=40)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ItemVendaRoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('roda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_em_vendas', to='estoque_rodas.roda')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_rodas', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Item de venda (roda)',
                'verbose_name_plural': 'Itens de venda (rodas)',
            },
        ),
        migrations.CreateModel(
            name='ImagemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='vendas/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Imagem da venda',
                'verbose_name_plural': 'Imagens da venda',
                'ordering': ['data_cadastro'],
            },
        ),
    ]
