# Generated by Django 6.0.2 on 2026-05-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('reservada_nao_paga', 'Reservada - não paga'), ('reservada_paga', 'Reservada - paga'), ('aguardando_pagamento', 'Aguardando pagamento'), ('paga_aguardando_retirada', 'Paga - aguardando retirada'), ('paga_aguardando_entrega', 'Paga - aguardando entrega'), ('finalizada_retirada', 'Finalizada - retirada pelo cliente'), ('finalizada_entregue', 'Finalizada - entregue'), ('cancelada', 'Cancelada')], default='orcamento', max_length=40),
        ),
    ]
