# Generated by Django 6.0.2 on 2026-06-02 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda', '-data_cadastro'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
