# Generated by Django 6.0.2 on 2026-05-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_venda_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemVendaInsumo',
        ),
    ]
