# Generated by Django 6.0.2 on 2026-04-19 00:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('quantidade_inicial', models.PositiveIntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('l', 'Litro'), ('m', 'Metro'), ('cx', 'Caixa'), ('pct', 'Pacote')], default='un', max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque_insumos.insumo')),
            ],
            options={
                'verbose_name': 'Movimentação de insumo',
                'verbose_name_plural': 'Movimentações de insumos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.DeleteModel(
            name='MovimentacaoRoda',
        ),
        migrations.DeleteModel(
            name='Roda',
        ),
    ]
