# Generated by Django 6.0.2 on 2026-03-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_endereco_cidade_remove_endereco_rua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
