# Generated by Django 6.0.2 on 2026-04-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_insumos', '0002_insumo_movimentacaoinsumo_delete_movimentacaoroda_and_more'),
        ('estoque_rodas', '0005_roda_quantidade_inicial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='valor',
            new_name='valor_total',
        ),
        migrations.CreateModel(
            name='ImagemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='servicos/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Imagem do serviço',
                'verbose_name_plural': 'Imagens do serviço',
                'ordering': ['data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ItemServicoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_em_servicos', to='estoque_insumos.insumo')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_insumos', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Item de serviço (insumo)',
                'verbose_name_plural': 'Itens de serviço (insumos)',
            },
        ),
        migrations.CreateModel(
            name='ItemServicoRoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('roda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_em_servicos', to='estoque_rodas.roda')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_rodas', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Item de serviço (roda)',
                'verbose_name_plural': 'Itens de serviço (rodas)',
            },
        ),
    ]
