# Generated by Django 6.0.2 on 2026-05-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_rename_valor_servico_valor_total_imagemservico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('finalizada_aguardando_cliente', 'Finalizado - aguardando cliente'), ('finalizada_entregue', 'Finalizado - entregue'), ('cancelado', 'Cancelado')], default='aberto', max_length=40),
        ),
    ]
