# Generated by Django 6.0.2 on 2026-05-04 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso_clientes', models.BooleanField(default=False)),
                ('acesso_estoque_rodas', models.BooleanField(default=False)),
                ('acesso_estoque_insumos', models.BooleanField(default=False)),
                ('acesso_servicos', models.BooleanField(default=False)),
                ('acesso_vendas', models.BooleanField(default=False)),
                ('acesso_despesas', models.BooleanField(default=False)),
                ('acesso_usuarios', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissao_rodagest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
