# Generated by Django 6.0.2 on 2026-05-03 00:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('agua', 'Água'), ('energia', 'Energia'), ('internet', 'Internet'), ('telefone', 'Telefone'), ('aluguel', 'Aluguel'), ('boleto', 'Boleto'), ('fornecedor', 'Fornecedor'), ('manutencao', 'Manutenção'), ('imposto_taxa', 'Imposto ou taxa'), ('material_consumo', 'Material de consumo'), ('salario', 'Salário'), ('transporte', 'Transporte'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_debito', 'Cartão de débito'), ('cartao_credito', 'Cartão de crédito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('outros', 'Outros')], default='pix', max_length=30)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
