# Generated by Django 6.0.2 on 2026-05-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='despesas/')),
                ('nome_original', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='despesas.despesa')),
            ],
            options={
                'verbose_name': 'Arquivo da despesa',
                'verbose_name_plural': 'Arquivos da despesa',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
