# Generated by Django 6.0.2 on 2026-03-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(choices=[('nova', 'Nova'), ('usada', 'Usada'), ('reformada', 'Reformada')], default='nova', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Roda',
                'verbose_name_plural': 'Rodas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoRoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('roda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque_rodas.roda')),
            ],
            options={
                'verbose_name': 'Movimentação de roda',
                'verbose_name_plural': 'Movimentações de rodas',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
