# Generated by Django 6.0.2 on 2026-03-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_rodas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roda',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
