# Generated by Django 6.0.2 on 2026-03-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_rodas', '0002_roda_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='roda',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
