# Generated by Django 6.0.2 on 2026-03-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_rodas', '0003_roda_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roda',
            name='estado',
            field=models.CharField(choices=[('nova', 'Nova'), ('usada', 'Usada'), ('reformada', 'Reformada')], max_length=20),
        ),
    ]
