# Generated by Django 6.0.2 on 2026-03-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_rodas', '0004_alter_roda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='roda',
            name='quantidade_inicial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
